# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Outrig < Formula
  desc "Observability monitor for Go programs during development time"
  homepage "https://github.com/outrigdev/outrig"
  version "0.9.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/outrigdev/outrig/releases/download/v0.9.1/outrig_0.9.1_Darwin_x86_64.tar.gz"
      sha256 "36a8f9d98c60d41893f9cb2975e9d3f435dd81ad8a728142d6a6dc5a6e119e4b"

      def install
        bin.install "outrig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/outrigdev/outrig/releases/download/v0.9.1/outrig_0.9.1_Darwin_arm64.tar.gz"
      sha256 "f3a7269ba2c3b8f27a3b1a2cf714b2aea2cecdb0fcdf89fbf6073b4a04ed7782"

      def install
        bin.install "outrig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/outrigdev/outrig/releases/download/v0.9.1/outrig_0.9.1_Linux_x86_64.tar.gz"
        sha256 "88d530991d576187429a0f18baa3ff3e63f894d307e78e665ecad33dac4a64b3"

        def install
          bin.install "outrig"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/outrigdev/outrig/releases/download/v0.9.1/outrig_0.9.1_Linux_arm64.tar.gz"
        sha256 "f3fc45b0bb664f12147a0f860ac2b8a3a0e5ea2ac403430273bd10ef5551df50"

        def install
          bin.install "outrig"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Outrig has been installed successfully!

      Quick start and docs:
      https://outrig.run/docs/quickstart

      To start the Outrig server manually (foreground):
        outrig server

      To load and start Outrig as a background service (recommended):
        brew services start outrig

      ---
      Outrig is open source and free for individual users.
      If you find it useful, please star us on GitHub:
        https://github.com/outrigdev/outrig
      ---
    EOS
  end

  service do
    run [opt_bin/"outrig", "server"]
    keep_alive false
    log_path var/"log/outrig.log"
    error_log_path var/"log/outrig.log"
    working_dir var
  end

  test do
    system "#{bin}/outrig", "version"
  end
end
