# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Outrig < Formula
  desc "Observability monitor for Go programs during development time"
  homepage "https://github.com/outrigdev/outrig"
  version "0.4.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/outrigdev/outrig/releases/download/v0.4.5/outrig_0.4.5_Darwin_x86_64.tar.gz"
      sha256 "e39a2ba19955bcc82fb5590440b2a877b15c42a06ff220138b4c86a70bee95d6"

      def install
        bin.install "outrig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/outrigdev/outrig/releases/download/v0.4.5/outrig_0.4.5_Darwin_arm64.tar.gz"
      sha256 "e11d1aa5e00e04e4ca2371392ba50e4170243e06bb8dd0267ce10e5ccb8be3d3"

      def install
        bin.install "outrig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/outrigdev/outrig/releases/download/v0.4.5/outrig_0.4.5_Linux_x86_64.tar.gz"
        sha256 "def259abab45ebc18cb5e44ba76a7eb31aad4d4196c827ab7979065feb86beda"

        def install
          bin.install "outrig"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/outrigdev/outrig/releases/download/v0.4.5/outrig_0.4.5_Linux_arm64.tar.gz"
        sha256 "3e64494545ac088a790c3dfe40c12aedab74495b05db5ffc42915b1148c70ed7"

        def install
          bin.install "outrig"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Outrig has been installed successfully!

      Quick start and docs:
        https://outrig.run/docs/quickstart

      To start the Outrig server:
        outrig server

      ---
      Outrig is open source and free for individual users.
      If you find it useful, please star us on GitHub:
        https://github.com/outrigdev/outrig
      ---
    EOS
  end

  test do
    system "#{bin}/outrig", "version"
  end
end
