# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Outrig < Formula
  desc "Real-time debugging for Go programs, similar to Chrome DevTools"
  homepage "https://github.com/outrigdev/outrig"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/outrigdev/outrig/releases/download/v0.3.1/outrig_0.3.1_Darwin_x86_64.tar.gz"
      sha256 "247d53c92d80cc080ff5a7ddf01b31127fb1b7a495db42fae81f46397feab42f"

      def install
        bin.install "outrig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/outrigdev/outrig/releases/download/v0.3.1/outrig_0.3.1_Darwin_arm64.tar.gz"
      sha256 "0429e873bb4cfb4cfb5fa6a91398b6d1fb79387c9269392cf662308dd76869b2"

      def install
        bin.install "outrig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/outrigdev/outrig/releases/download/v0.3.1/outrig_0.3.1_Linux_x86_64.tar.gz"
        sha256 "5fccda145350603f21425e715ee37710384029593b4aaca638d0d17cb72422fb"

        def install
          bin.install "outrig"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/outrigdev/outrig/releases/download/v0.3.1/outrig_0.3.1_Linux_arm64.tar.gz"
        sha256 "594b706d008ba66c26eaf1de3d84d12266fe3369ae1092f1b968f9f5d3eb0975"

        def install
          bin.install "outrig"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Outrig has been installed successfully!

      Quick start and docs:
        https://outrig.run/docs/quickstart

      To start the Outrig server:
        outrig server

      ---
      Outrig is open source and free for individual users.
      If you find it useful, please star us on GitHub:
        https://github.com/outrigdev/outrig
    EOS
  end

  test do
    system "#{bin}/outrig", "version"
  end
end
